### ISSUE TITLE
Move the Switch to User button on Customer card view

### ISSUE THREAD

**Issue by SDavisMedia** [awesomemotive/edd-dev-tools#15]
### The Problem

On the Customer card view, there's an alignment issue with the `Switch to User` button and its siblings, as seen here: 
![44561353-0f26f600-a71a-11e8-82bd-69325686f151](https://user-images.githubusercontent.com/2359131/44819468-d23b8300-aba1-11e8-9f0f-c12dc53f966b.png)

See short discussion about why this happens and why we should fix it here instead of in EDD. https://github.com/easydigitaldownloads/easy-digital-downloads/issues/6870

### Replication

On **EDD 3.0**, activate the **User Switching** plugin and **EDD Dev Tools**, then view a Customer card (requires that the customer be linked to a WP user account).

### Proposal

Let's find a new place for the `Switch to User` button/link. Thoughts, @cklosowski?

**Comment by cklosowski** [comment]
Yeah i'll find a new spot for it. :+1:

**Comment by robincornett** [comment]
I think we can actually close this as a `wontfix` as the CSS changes in EDD 3.0 have resolved the issue (at least for me from what I see):

![image](https://user-images.githubusercontent.com/4853066/165536511-ddf64b79-5c3e-485c-bfbe-13360a90dbfc.png)

**Comment by mihaijoldis** [comment]
This appears fixed to me too in realease/3.0 just like the screenshot from @robincornett

**Comment by robincornett** [comment]
Thanks for confirming, @mihaijoldis, going ahead and closing then.
